INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Afghanistan','AF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Albania','AL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Algeria','DZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Andorra','AD');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Angola','AO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Anguilla','AI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Antigua and Barbuda','AG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Argentina','AR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Armenia','AM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Aruba','AW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Australia','AU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Austria','AT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Azerbaijan','AZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bahamas','BS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bahrain','BH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bangladesh','BD');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Barbados','BB');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Belarus','BY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Belgium','BE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Belize','BZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Benin','BJ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bermuda','BM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bhutan','BT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bosnia and Herzegovina','BA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Botswana','BW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bouvet Island','BV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Brazil','BR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('British Indian Ocean Territory','IO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Brunei','BN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Bulgaria','BG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Burkina Faso','BF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Burundi','BI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cambodia','KH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cameroon','CM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Canada','CA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cape Verde','CV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cayman Islands','KY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Central African Republic','CF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Chad','TD');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Chile','CL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('China','CN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Christmas Island','CX');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cocos (Keeling) Islands','CC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Colombia','CO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Comoros','KM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Congo','CG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cook Islands','CK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Costa Rica','CR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Croatia','HR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cuba','CU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Cyprus','CY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Czech Republic','CZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Denmark','DK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Djibouti','DJ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Dominica','DM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Dominican Republic','DO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Ecuador','EC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Egypt','EG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('El Salvador','SV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Equatorial Guinea','GQ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Eritrea','ER');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Estonia','EE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Ethiopia','ET');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Falkland Islands','FK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Faroe Islands','FO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Fiji','FJ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Finland','FI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('France','FR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('French Polynesia','PF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Gabon','GA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Gambia','GM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Georgia','GE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Germany','DE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Ghana','GH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Gibraltar','GI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Greece','GR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Greenland','GL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Grenada','GD');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guadeloupe','GP');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guam','GU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guatemala','GT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guernsey','GG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guinea','GN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guinea-Bissau','GW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Guyana','GY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Haiti','HT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Heard Island and McDonald Islands','HM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Vatican City State (Holy See)','VA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Honduras','HN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Hong Kong','HK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Hungary','HU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Iceland','IS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('India','IN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Indonesia','ID');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Iran','IR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Iraq','IQ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Ireland','IE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Isle of Man','IM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Israel','IL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Italy','IT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Jamaica','JM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Japan','JP');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Jersey','JE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Jordan','JO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Kazakhstan','KZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Kenya','KE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Kiribati','KI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Kuwait','KW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Kyrgyzstan','KG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Laos','LA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Latvia','LV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Lebanon','LB');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Lesotho','LS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Liberia','LR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Liechtenstein','LI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Lithuania','LT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Luxembourg','LU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Macau','MO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Madagascar','MG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Malawi','MW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Malaysia','MY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Maldives','MV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mali','ML');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Malta','MT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Marshall Islands','MH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Martinique','MQ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mauritania','MR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mauritius','MU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mayotte','YT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mexico','MX');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Monaco','MC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mongolia','MN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Montenegro','ME');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Montserrat','MS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Morocco','MA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Mozambique','MZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Myanmar','MM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Namibia','NA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Nauru','NR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Nepal','NP');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Netherlands','NL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('New Caledonia','NC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('New Zealand','NZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Nicaragua','NI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Niger','NE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Nigeria','NG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Niue','NU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Norfolk Island','NF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Northern Mariana Islands','MP');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Norway','NO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Oman','OM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Pakistan','PK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Palau','PW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Panama','PA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Papua New Guinea','PG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Paraguay','PY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Peru','PE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Philippines','PH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Pitcairn','PN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Poland','PL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Portugal','PT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Puerto Rico','PR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Qatar','QA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Réunion','RE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Romania','RO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Russia','RU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Rwanda','RW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Saint Kitts and Nevis','KN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Saint Lucia','LC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Saint Pierre and Miquelon','PM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Saint Vincent and the Grenadines','VC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Samoa','WS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('San Marino','SM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Sao Tome and Principe','ST');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Saudi Arabia','SA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Senegal','SN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Serbia','RS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Seychelles','SC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Sierra Leone','SL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Singapore','SG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Slovakia','SK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Slovenia','SI');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Solomon Islands','SB');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Somalia','SO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('South Africa','ZA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('South Georgia and the South Sandwich Islands','GS');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Spain','ES');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Sri Lanka','LK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Sudan','SD');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Suriname','SR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Swaziland','SZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Sweden','SE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Switzerland','CH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Syria','SY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Taiwan','TW');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Tajikistan','TJ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Thailand','TH');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Timor-Leste','TL');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Togo','TG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Tokelau','TK');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Tonga','TO');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Trinidad and Tobago','TT');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Tunisia','TN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Turkey','TR');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Turkmenistan','TM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Turks and Caicos Islands','TC');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Tuvalu','TV');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Uganda','UG');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Ukraine','UA');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('United Arab Emirates','AE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('United Kingdom','GB');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('United States','US');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('United States Minor Outlying Islands','UM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Uruguay','UY');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Uzbekistan','UZ');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Vanuatu','VU');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Venezuela','VE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Vietnam','VN');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Wallis and Futuna','WF');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Yemen','YE');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Zambia','ZM');
INSERT INTO TblCountries(CountryName,CountryCode) VALUES ('Zimbabwe','ZW');


Select * from TblCountries
